-- Généré par Oracle SQL Developer Data Modeler 4.1.3.901
--   à :        2016-10-15 17:37:44 EDT
--   site :      Oracle Database 12c
--   type :      Oracle Database 12c




CREATE TABLE AVAILABILITY
  (
    ID_PRODUCT           VARCHAR2 (20) NOT NULL ,
    ID_PHARMACY          VARCHAR2 (20) NOT NULL ,
    QUANTITY             NUMBER ,
    CURRENT_PRICE        NUMBER ,
    LASTEST_REFRESH_TIME TIMESTAMP
  ) ;


CREATE TABLE COUNTRY
  (
    COUNTRY_ID   VARCHAR2 (20) NOT NULL ,
    COUNTRY_NAME VARCHAR2 (200) NOT NULL
  ) ;
ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( COUNTRY_ID ) ;


CREATE TABLE DEVICE
  (
    DEVICE_ID       VARCHAR2 (20) NOT NULL ,
    DEVICE_TYPE_ID  VARCHAR2 (20) NOT NULL ,
    MANUFACTURER_ID VARCHAR2 (20) NOT NULL ,
    DEVICE_NAME     VARCHAR2 (200)
  ) ;
ALTER TABLE DEVICE ADD CONSTRAINT DEVICE_PK PRIMARY KEY ( DEVICE_ID ) ;


CREATE TABLE DEVICE_MANUFACTURER
  (
    MANUFACTURER_ID   VARCHAR2 (20) NOT NULL ,
    MANUFACTURER_NAME VARCHAR2 (200)
  ) ;
ALTER TABLE DEVICE_MANUFACTURER ADD CONSTRAINT DEVICE_MANUFACTURER_PK PRIMARY KEY ( MANUFACTURER_ID ) ;


CREATE TABLE DEVICE_TYPE
  (
    DEVICE_TYPE_ID   VARCHAR2 (20) NOT NULL ,
    DEVICE_TYPE_NAME VARCHAR2 (200)
  ) ;
ALTER TABLE DEVICE_TYPE ADD CONSTRAINT DEVICE_TYPE_PK PRIMARY KEY ( DEVICE_TYPE_ID ) ;


CREATE TABLE DISEASE
  (
    DISEASE_ID   VARCHAR2 (20) NOT NULL ,
    DISEASE_NAME VARCHAR2 (200)
  ) ;
ALTER TABLE DISEASE ADD CONSTRAINT DISEASE_PK PRIMARY KEY ( DISEASE_ID ) ;


CREATE TABLE DISTRICT
  (
    DISTRICT_ID   VARCHAR2 (20) NOT NULL ,
    DISTRICT_NAME VARCHAR2 (500) ,
    TOWN_ID       VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE DISTRICT ADD CONSTRAINT DISTRICT_PK PRIMARY KEY ( DISTRICT_ID ) ;


CREATE TABLE EMPLOYEE
  (
    ID_PHARMACY     VARCHAR2 (20) NOT NULL ,
    ID_PERSON       VARCHAR2 (20) NOT NULL ,
    WORK_START_DATE DATE ,
    WORK_END_DATE   DATE ,
    SHIFT_START     DATE ,
    SHIFT_END       DATE
  ) ;
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY ( ID_PERSON ) ;


CREATE TABLE HOSPITAL
  (
    ID_HOSPITAL         VARCHAR2 (20) NOT NULL ,
    HOSPITAL_NAME       VARCHAR2 (100) ,
    LOCATION            VARCHAR2 (20) NOT NULL ,
    HOSP_ADDRESS        VARCHAR2 (500) ,
    CURRENT_CONST_PRICE NUMBER ,
    ON_DUTY             NUMBER
  ) ;
ALTER TABLE HOSPITAL ADD CONSTRAINT HOSPITAL_PK PRIMARY KEY ( ID_HOSPITAL ) ;


CREATE TABLE LANGAGE
  (
    LANG_ID  VARCHAR2 (20) NOT NULL ,
    LANGUAGE VARCHAR2 (200)
  ) ;
ALTER TABLE LANGAGE ADD CONSTRAINT LANGUAGE_PK PRIMARY KEY ( LANG_ID ) ;


CREATE TABLE LANGUAGE_SKILLS
  (
    LANG_ID   VARCHAR2 (20) NOT NULL ,
    PERSON_ID VARCHAR2 (20) NOT NULL ,
    READ      VARCHAR2 (10) ,
    WRITTEN   VARCHAR2 (10) ,
    SPOKEN    VARCHAR2 (10)
  ) ;
ALTER TABLE LANGUAGE_SKILLS ADD CONSTRAINT LANGUAGE_SKILLS_PK PRIMARY KEY ( LANG_ID, PERSON_ID ) ;


CREATE TABLE PERSON
  (
    ID_PERSON  VARCHAR2 (20) NOT NULL ,
    FRIST_NAME VARCHAR2 (500) ,
    LAST_NAME  VARCHAR2 (500) ,
    LANGAGE    VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE PERSON ADD CONSTRAINT PERSON_PK PRIMARY KEY ( ID_PERSON ) ;


CREATE TABLE PHARMACY
  (
    ID_PHARMACY        VARCHAR2 (20) NOT NULL ,
    PHARMACY_NAME      VARCHAR2 (500) ,
    LOCATION           VARCHAR2 (20) NOT NULL ,
    PHARMACY_ADDRESS   VARCHAR2 (500) ,
    PHONE_NUMBER       VARCHAR2 (100) ,
    FAX                VARCHAR2 (100) ,
    APP_MANAGER        VARCHAR2 (50) NOT NULL ,
    EMPLOYEE_ID_PERSON VARCHAR2 (20) NOT NULL ,
    ON_DUTY            NUMBER
  ) ;
ALTER TABLE PHARMACY ADD CONSTRAINT PHAMACY_PK PRIMARY KEY ( ID_PHARMACY ) ;


CREATE TABLE PREMISE
  (
    PREMISE_ID   VARCHAR2 (20) NOT NULL ,
    DISTRICT_ID  VARCHAR2 (20) NOT NULL ,
    PREMISE_NAME VARCHAR2 (500)
  ) ;
ALTER TABLE PREMISE ADD CONSTRAINT PREMISE_PK PRIMARY KEY ( PREMISE_ID ) ;


CREATE TABLE PRODUCT
  (
    ID_PRODUCT      VARCHAR2 (20) NOT NULL ,
    ID_PRODUCT_TYPE VARCHAR2 (20) NOT NULL ,
    ID_MANUFACTURER VARCHAR2 (20) NOT NULL ,
    TRADE_NAME      VARCHAR2 (500) ,
    TREATMENT       VARCHAR2 (20) NOT NULL ,
    GENERIC         NUMBER
  ) ;
ALTER TABLE PRODUCT ADD CONSTRAINT MEDECINE_PK PRIMARY KEY ( ID_PRODUCT ) ;


CREATE TABLE PRODUCT_MANUFACTURER
  (
    ID_MANUFACTURER      VARCHAR2 (20) NOT NULL ,
    MANUFACTURER_NAME    VARCHAR2 (200) ,
    MANUFACTURER_ADDRESS VARCHAR2 (500)
  ) ;
ALTER TABLE PRODUCT_MANUFACTURER ADD CONSTRAINT PRODUCT_MANUFACTURER_PK PRIMARY KEY ( ID_MANUFACTURER ) ;


CREATE TABLE PRODUCT_TYPE
  (
    ID_PRODUCT_TYPE   VARCHAR2 (20) NOT NULL ,
    PRODUCT_TYPE_NAME VARCHAR2 (200)
  ) ;
ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY ( ID_PRODUCT_TYPE ) ;


CREATE TABLE SEARCH
  (
    ID_USER         VARCHAR2 (50) NOT NULL ,
    ID_PRODUCT      VARCHAR2 (20) NOT NULL ,
    SEARCH_TIME     TIMESTAMP ,
    USED_DEVICE     VARCHAR2 (20) NOT NULL ,
    SEARCH_LOCATION VARCHAR2 (20) NOT NULL ,
    USER_DEVICE_ID  VARCHAR2 (20) NOT NULL ,
    USER_ID_PERSON  VARCHAR2 (20) NOT NULL
  ) ;


CREATE TABLE SUBSTITUTE
  (
    MASTER_PRODUCT  VARCHAR2 (20) NOT NULL ,
    SUBSTITUTE_PROD VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE SUBSTITUTE ADD CONSTRAINT SUBSTITUTE_PK PRIMARY KEY ( MASTER_PRODUCT, SUBSTITUTE_PROD ) ;


CREATE TABLE TOWN
  (
    TOWN_ID      VARCHAR2 (20) NOT NULL ,
    TOWN_NAME    VARCHAR2 (200) ,
    COUNTRY_ID   VARCHAR2 (20) NOT NULL ,
    COUNTRY_NAME VARCHAR2 (200) NOT NULL
  ) ;
ALTER TABLE TOWN ADD CONSTRAINT TOWN_PK PRIMARY KEY ( TOWN_ID ) ;


CREATE TABLE TREATMENT
  (
    DISEASE_ID VARCHAR2 (20) NOT NULL ,
    PRODUCT_ID VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE TREATMENT ADD CONSTRAINT TREATMENT_PK PRIMARY KEY ( DISEASE_ID, PRODUCT_ID ) ;


CREATE TABLE "USER"
  (
    ID_PERSON VARCHAR2 (20) NOT NULL ,
    DEVICE_ID VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE "USER" ADD CONSTRAINT USER_PK PRIMARY KEY ( DEVICE_ID, ID_PERSON ) ;


ALTER TABLE AVAILABILITY ADD CONSTRAINT AVAILABILITY_PHAMACY_FK FOREIGN KEY ( ID_PHARMACY ) REFERENCES PHARMACY ( ID_PHARMACY ) ;

ALTER TABLE DEVICE ADD CONSTRAINT DEVICE_DEVICE_MANUFACTURER_FK FOREIGN KEY ( MANUFACTURER_ID ) REFERENCES DEVICE_MANUFACTURER ( MANUFACTURER_ID ) ;

ALTER TABLE DEVICE ADD CONSTRAINT DEVICE_DEVICE_TYPE_FK FOREIGN KEY ( DEVICE_TYPE_ID ) REFERENCES DEVICE_TYPE ( DEVICE_TYPE_ID ) ;

ALTER TABLE DISTRICT ADD CONSTRAINT DISTRICT_TOWN_FK FOREIGN KEY ( TOWN_ID ) REFERENCES TOWN ( TOWN_ID ) ;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_PERSON_FK FOREIGN KEY ( ID_PERSON ) REFERENCES PERSON ( ID_PERSON ) ;

ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_PHARMACY_FK FOREIGN KEY ( ID_PHARMACY ) REFERENCES PHARMACY ( ID_PHARMACY ) ;

ALTER TABLE HOSPITAL ADD CONSTRAINT HOSPITAL_PREMISE_FK FOREIGN KEY ( LOCATION ) REFERENCES PREMISE ( PREMISE_ID ) ;

ALTER TABLE LANGUAGE_SKILLS ADD CONSTRAINT LANGUAGE_SKILLS_LANGAGE_FK FOREIGN KEY ( LANG_ID ) REFERENCES LANGAGE ( LANG_ID ) ;

ALTER TABLE PERSON ADD CONSTRAINT PERSON_LANGUAGE_FK FOREIGN KEY ( LANGAGE ) REFERENCES LANGAGE ( LANG_ID ) ;

ALTER TABLE PHARMACY ADD CONSTRAINT PHAMACY_PREMISE_FK FOREIGN KEY ( LOCATION ) REFERENCES PREMISE ( PREMISE_ID ) ;

ALTER TABLE PHARMACY ADD CONSTRAINT PHARMACY_EMPLOYEE_FK FOREIGN KEY ( EMPLOYEE_ID_PERSON ) REFERENCES EMPLOYEE ( ID_PERSON ) ;

ALTER TABLE PREMISE ADD CONSTRAINT PREMISE_DISTRICT_FK FOREIGN KEY ( DISTRICT_ID ) REFERENCES DISTRICT ( DISTRICT_ID ) ;

ALTER TABLE AVAILABILITY ADD CONSTRAINT PRODUCT_PHARMACY_FK FOREIGN KEY ( ID_PRODUCT ) REFERENCES PRODUCT ( ID_PRODUCT ) ;

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PRODUCT_MANU_FK FOREIGN KEY ( ID_MANUFACTURER ) REFERENCES PRODUCT_MANUFACTURER ( ID_MANUFACTURER ) ;

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PRODUCT_TYPE_FK FOREIGN KEY ( ID_PRODUCT_TYPE ) REFERENCES PRODUCT_TYPE ( ID_PRODUCT_TYPE ) ;

ALTER TABLE SEARCH ADD CONSTRAINT SEARCH_DEVICE_FK FOREIGN KEY ( USED_DEVICE ) REFERENCES DEVICE ( DEVICE_ID ) ;

ALTER TABLE SEARCH ADD CONSTRAINT SEARCH_MEDECINE_FK FOREIGN KEY ( ID_PRODUCT ) REFERENCES PRODUCT ( ID_PRODUCT ) ;

ALTER TABLE SEARCH ADD CONSTRAINT SEARCH_PREMISE_FK FOREIGN KEY ( SEARCH_LOCATION ) REFERENCES PREMISE ( PREMISE_ID ) ;

ALTER TABLE SEARCH ADD CONSTRAINT SEARCH_USER_FK FOREIGN KEY ( USER_DEVICE_ID, USER_ID_PERSON ) REFERENCES "USER" ( DEVICE_ID, ID_PERSON ) ;

ALTER TABLE SUBSTITUTE ADD CONSTRAINT SUBSTITUTE_PRODUCT_FK FOREIGN KEY ( MASTER_PRODUCT ) REFERENCES PRODUCT ( ID_PRODUCT ) ;

ALTER TABLE SUBSTITUTE ADD CONSTRAINT SUBSTITUTE_PRODUCT_FKv2 FOREIGN KEY ( SUBSTITUTE_PROD ) REFERENCES PRODUCT ( ID_PRODUCT ) ;

ALTER TABLE LANGUAGE_SKILLS ADD CONSTRAINT TABLE_23_PERSON_FK FOREIGN KEY ( PERSON_ID ) REFERENCES PERSON ( ID_PERSON ) ;

ALTER TABLE TOWN ADD CONSTRAINT TOWN_COUNTRY_FK FOREIGN KEY ( COUNTRY_ID ) REFERENCES COUNTRY ( COUNTRY_ID ) ;

ALTER TABLE TREATMENT ADD CONSTRAINT TREATMENT_DISEASE_FK FOREIGN KEY ( DISEASE_ID ) REFERENCES DISEASE ( DISEASE_ID ) ;

ALTER TABLE TREATMENT ADD CONSTRAINT TREATMENT_PRODUCT_FK FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT ( ID_PRODUCT ) ;

ALTER TABLE "USER" ADD CONSTRAINT USER_DEVICE_FK FOREIGN KEY ( DEVICE_ID ) REFERENCES DEVICE ( DEVICE_ID ) ;

ALTER TABLE "USER" ADD CONSTRAINT USER_PERSON_FK FOREIGN KEY ( ID_PERSON ) REFERENCES PERSON ( ID_PERSON ) ;


-- Rapport récapitulatif d'Oracle SQL Developer Data Modeler : 
-- 
-- CREATE TABLE                            22
-- CREATE INDEX                             0
-- ALTER TABLE                             47
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

